// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9EB2ULvQv9a8Z-xjoRtGSY5VLjeSYTNA',
    appId: '1:889512449351:web:60dc9920a181ba72452862',
    messagingSenderId: '889512449351',
    projectId: 'read-ludhiana-read',
    authDomain: 'read-ludhiana-read.firebaseapp.com',
    storageBucket: 'read-ludhiana-read.appspot.com',
    measurementId: 'G-RMTJ0YLYYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrXzjbHaIhGqa0oGKs0-Ml_rMnoWlzpwQ',
    appId: '1:889512449351:android:2050e067dff12f9f452862',
    messagingSenderId: '889512449351',
    projectId: 'read-ludhiana-read',
    storageBucket: 'read-ludhiana-read.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmxcpiEN8SiY1epEJFZB9qBNN46-oiUZc',
    appId: '1:889512449351:ios:50ca3d8e6866dbf9452862',
    messagingSenderId: '889512449351',
    projectId: 'read-ludhiana-read',
    storageBucket: 'read-ludhiana-read.appspot.com',
    androidClientId: '889512449351-hbquks85m56c1fcdmng6mneuov8la8ft.apps.googleusercontent.com',
    iosClientId: '889512449351-4q7nn1bolmo3kpafp97df6ncgoshr046.apps.googleusercontent.com',
    iosBundleId: 'com.auribises.rlr',
  );
}
